<?php
use Shetabit\Shopit\Database\CreateProductSpecificationSpecificationValueTable as BaseCreateProductSpecificationSpecificationValueTable;

class CreateProductSpecificationSpecificationValueTable extends BaseCreateProductSpecificationSpecificationValueTable {}