<?php
use Shetabit\Shopit\Database\CreateAdvertisementPositionsTable as BaseCreateAdvertisementPositionsTable;

class CreateAdvertisementPositionsTable extends BaseCreateAdvertisementPositionsTable {}